<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-U7EES6NV" ignored="0" name="GetTransportFee" tests="50" failures="7" timestamp="26 十二月 2018 07:11:06 GMT" time="7.997" errors="0">
  <testcase name="test_Login1" time="0.855" classname="com.edu.test.loginTest"/>
  <testcase name="test_Login10" time="0.091" classname="com.edu.test.loginTest"/>
  <testcase name="test_Login11" time="0.086" classname="com.edu.test.loginTest"/>
  <testcase name="test_Login12" time="0.078" classname="com.edu.test.loginTest"/>
  <testcase name="test_Login2" time="0.099" classname="com.edu.test.loginTest"/>
  <testcase name="test_Login3" time="0.092" classname="com.edu.test.loginTest"/>
  <testcase name="test_Login4" time="0.099" classname="com.edu.test.loginTest"/>
  <testcase name="test_Login5" time="0.073" classname="com.edu.test.loginTest"/>
  <testcase name="test_Login6" time="0.076" classname="com.edu.test.loginTest"/>
  <testcase name="test_Login7" time="0.087" classname="com.edu.test.loginTest"/>
  <testcase name="test_Login8" time="0.087" classname="com.edu.test.loginTest"/>
  <testcase name="test_Login9" time="0.078" classname="com.edu.test.loginTest"/>
  <testcase name="testSkuList1" time="0.092" classname="com.edu.test.SkuListTest"/>
  <testcase name="testSkuList2" time="0.1" classname="com.edu.test.SkuListTest"/>
  <testcase name="testSkuList6" time="0.114" classname="com.edu.test.SkuListTest">
    <failure type="java.lang.Exception" message="the Text: &amp;apos;header&amp;apos; is not Present!">
      <![CDATA[java.lang.Exception: the Text: 'header' is not Present!
at com.edu.utils.Checker.verifyTextPresent(Unknown Source)
at com.edu.test.SkuListTest.testSkuList6(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testSkuList6 -->
  <testcase name="testSkuLlist3" time="0.094" classname="com.edu.test.SkuListTest">
    <failure type="java.lang.Exception" message="the Text: &amp;apos;ID&amp;apos; is not Present!">
      <![CDATA[java.lang.Exception: the Text: 'ID' is not Present!
at com.edu.utils.Checker.verifyTextPresent(Unknown Source)
at com.edu.test.SkuListTest.testSkuLlist3(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testSkuLlist3 -->
  <testcase name="testSkuLlist4" time="0.085" classname="com.edu.test.SkuListTest"/>
  <testcase name="KonDetail" time="0.256" classname="com.edu.test.JK">
    <failure type="java.lang.AssertionError" message="expected [success] but found [最多只能添加6个地址]">
      <![CDATA[java.lang.AssertionError: expected [success] but found [最多只能添加6个地址]
at com.edu.utils.Checker.assertXpath(Unknown Source)
at com.edu.test.JK.KonDetail(Unknown Source)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- KonDetail -->
  <testcase name="KonreceiverName" time="0.164" classname="com.edu.test.JK">
    <failure type="java.lang.AssertionError" message="expected [failure] but found [最多只能添加6个地址]">
      <![CDATA[java.lang.AssertionError: expected [failure] but found [最多只能添加6个地址]
at com.edu.utils.Checker.assertXpath(Unknown Source)
at com.edu.test.JK.KonreceiverName(Unknown Source)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- KonreceiverName -->
  <testcase name="newaddress" time="0.17" classname="com.edu.test.JK">
    <failure type="java.lang.AssertionError" message="expected [success] but found [最多只能添加6个地址]">
      <![CDATA[java.lang.AssertionError: expected [success] but found [最多只能添加6个地址]
at com.edu.utils.Checker.assertXpath(Unknown Source)
at com.edu.test.JK.newaddress(Unknown Source)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- newaddress -->
  <testcase name="newsameaddress" time="0.188" classname="com.edu.test.JK">
    <failure type="java.lang.AssertionError" message="expected [success] but found [最多只能添加6个地址]">
      <![CDATA[java.lang.AssertionError: expected [success] but found [最多只能添加6个地址]
at com.edu.utils.Checker.assertXpath(Unknown Source)
at com.edu.test.JK.newsameaddress(Unknown Source)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- newsameaddress -->
  <testcase name="testGetTranportFeeBySpecial" time="0.09" classname="com.edu.test.HttpClientForGetTransportFeeTest"/>
  <testcase name="testGetTransportFeeByAreaError" time="0.071" classname="com.edu.test.HttpClientForGetTransportFeeTest"/>
  <testcase name="testGetTransportFeeByCityAreaError" time="0.091" classname="com.edu.test.HttpClientForGetTransportFeeTest"/>
  <testcase name="testGetTransportFeeByCityError" time="0.082" classname="com.edu.test.HttpClientForGetTransportFeeTest"/>
  <testcase name="testGetTransportFeeByDirectly" time="0.071" classname="com.edu.test.HttpClientForGetTransportFeeTest"/>
  <testcase name="testGetTransportFeeById" time="0.074" classname="com.edu.test.HttpClientForGetTransportFeeTest"/>
  <testcase name="testGetTransportFeeByIdError" time="0.074" classname="com.edu.test.HttpClientForGetTransportFeeTest"/>
  <testcase name="testGetTransportFeeByMuni" time="0.075" classname="com.edu.test.HttpClientForGetTransportFeeTest"/>
  <testcase name="testGetTransportFeeByNullId" time="0.086" classname="com.edu.test.HttpClientForGetTransportFeeTest"/>
  <testcase name="testGetTransportFeeSuccess" time="0.077" classname="com.edu.test.HttpClientForGetTransportFeeTest"/>
  <testcase name="TestAddList1" time="0.187" classname="com.edu.test.AddList"/>
  <testcase name="TestAddList2" time="0.174" classname="com.edu.test.AddList"/>
  <testcase name="TestAddList3" time="0.183" classname="com.edu.test.AddList"/>
  <testcase name="TestAddList4" time="0.172" classname="com.edu.test.AddList"/>
  <testcase name="TestAddList5" time="0.222" classname="com.edu.test.AddList"/>
  <testcase name="TestAddList6" time="0.162" classname="com.edu.test.AddList"/>
  <testcase name="AddressDeleteFail1" time="0.198" classname="com.edu.test.QGDelete"/>
  <testcase name="AddressDeleteFail2" time="0.163" classname="com.edu.test.QGDelete"/>
  <testcase name="AddressDeleteFail3" time="0.184" classname="com.edu.test.QGDelete"/>
  <testcase name="AddressDeleteSuccess" time="0.18" classname="com.edu.test.QGDelete">
    <failure type="net.sf.json.JSONException" message="JSONObject[&amp;quot;list&amp;quot;] is not a JSONArray.">
      <![CDATA[net.sf.json.JSONException: JSONObject["list"] is not a JSONArray.
at net.sf.json.JSONObject.getJSONArray(JSONObject.java:2038)
at com.edu.test.QGDelete.Getid(Unknown Source)
at com.edu.test.QGDelete.AddressDeleteSuccess(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- AddressDeleteSuccess -->
  <testcase name="loginSuccess" time="0.1" classname="com.edu.test.SubmitTest"/>
  <testcase name="changjing4" time="0.31" classname="com.edu.test.ChangJing_test"/>
  <testcase name="testAddress" time="0.189" classname="com.edu.test.SceneTest"/>
  <testcase name="testSkuList" time="0.189" classname="com.edu.test.SceneTest"/>
  <testcase name="testSubmit" time="0.188" classname="com.edu.test.SceneTest"/>
  <testcase name="testTransport" time="0.203" classname="com.edu.test.SceneTest"/>
  <testcase name="submit" time="0.079" classname="com.edu.test.SubmitTest"/>
  <testcase name="submit11" time="0.05" classname="com.edu.test.SubmitTest"/>
  <testcase name="submit1" time="0.051" classname="com.edu.test.SubmitTest"/>
</testsuite> <!-- GetTransportFee -->
